title:            Katie B Click
tagline:          A beautiful site.
description:      A place for my words and photography.
canonical: http://roachhd.github.io/katiebclick
baseurl: /katiebclick
url: //roachhd.github.io/katiebclick

# Owner/author information
owner:
  name:           Katie B Click
  avatar:         avatar.png
  bio:            "Student & Photographer"
  email:          katiebclick@gmail.com
  twitter:        katiebclick
  github:         roachhd
  instagram:      katiebclick
  dribbble:       katiebclick
  disqus:         katiebclick
  location:       "Melbourne, VIC"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
#  - title: Blog
#    url: /index
  - title: Exegesis
    url: /exegesis
  - title: Katie Who?
    url: /about
  - title: Collections
    url: /collections


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Melbourne/Australia
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
